-- phpMyAdmin SQL Dump
-- version 4.7.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Nov 27, 2017 at 12:55 PM
-- Server version: 10.0.31-MariaDB-cll-lve
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `charliez_hosting`
--

-- --------------------------------------------------------

--
-- Table structure for table `files`
--

CREATE TABLE `files` (
  `id` int(10) NOT NULL,
  `iname` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `filename` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `prod_desc` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `primary_color` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `other_names` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `material` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `country` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `finishes` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `variations` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sizes` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `secondscsize` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `scid` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `secondscid` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `firsttilesize` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `secondtilesize` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `thirdtilesize` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `firsttileid` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `secondtileid` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `thirdtileid` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `files`
--

INSERT INTO `files` (`id`, `iname`, `filename`, `prod_desc`, `primary_color`, `other_names`, `material`, `country`, `finishes`, `variations`, `sizes`, `secondscsize`, `scid`, `secondscid`, `firsttilesize`, `secondtilesize`, `thirdtilesize`, `firsttileid`, `secondtileid`, `thirdtileid`) VALUES
(1, 'Absolute Black', 'Absolute-Black-Granite.jpg', 'Absolute Black granite is a solid black granite from India that has a very consistent color and texture. Absolute Black is recommended for both interior and exterior use to create beautiful granite countertops, floors, architectural features, and outdoor cladding.', 'Black', 'Jet Black,Jet Blacky,Nero Absolute,Telephone Black', 'Granite', 'India', 'Polished', 'LOW', '2 CM', '3 CM', 'RSL-ABSOBLACK', 'RSL-ABSOBLK-3CM', '11x11', '12x12', '24x24', 'TINDBLK1111', 'TINDBLK1212', 'TINDBLK2424'),
(3, 'Bain Brook Brown', 'UFW.PNG', 'Bain Brook granite is a brown medium variation granite with hints of cream, gray and black flecks.  This durable granite is available in both tiles and slabs and is recommended for both interior and exterior projects including landscaping, flooring, outdoor countertops and walls.', 'Brown', 'Bainbrook Brown', 'Granite', 'China', 'Polished', 'LOW', '2 CM', '3 CM', 'RSL-BAIBRBRN*', 'RSL-BAIBRBRN-3C*', '12x12', 'null', 'null', 'TBAIBRBRN12120.38P', 'null', 'null'),
(4, 'Baltic Brown', 'Baltic-Brown-Granite.jpg', 'Baltic Brown granite is an exquisite blend of browns and black with small flecks of lighter gray and tans.  This granite is ideal of both indoor and outdoor applications including BBQ counter surrounds, bathrooms, and countertops.', 'Brown', 'N/A', 'Granite', 'Finland', 'Polished', 'Medium', '2 CM', '3 CM', 'RSL-BALTIC*', 'RSL-BALTIC-3CM*', '12x12', '18x18', 'null', 'TBALBRN1212', 'TBALBRN1818', 'null'),
(5, 'Bianco Catalina', 'Bianco-Catalina-Granite.jpg', 'Bianco Catalina granite is a subtle speckled black, gray, and white granite ideal for both interior and exterior projects even in areas with freezing temperatures. Recommended uses include residential and commercial granite countertops, floors, landscaping projects, cladding, and interior walls.', 'White', 'Black & White,Salt & Pepper', 'Granite', 'China', 'Polished', 'Low', '2 CM', '3 CM', 'RSL-BIACTLN-2CM*', 'RSL-BIACTLN-3CM*', '12x12', 'null', 'null', 'TBIACTLN1212', 'null', 'null'),
(6, 'Bianco Romano', 'Bianco-Romano-Granite.jpg', 'Bianco Romano granite is perfect for indoor and outdoor applications including landscaping projects in climates with freezing temperatures. Bianco Romano is mostly shades of white and gray with small darker flecks of browns and blacks.', 'White', 'Romano White', 'Granite', 'Brazil', 'Polished', 'MEDIUM', '2 CM', '2 CM', 'RSL-BIANROMA*', 'RSL-BIANRO-CL-2*', '12x12', '12x24', 'null', 'TBIANROMA1212', 'TBIANROMA1224', 'null'),
(7, 'Black Galaxy', 'Black-Galaxy-Granite.jpg', 'Black Galaxy granite is a mostly black granite with small gold or white flecks. Black Galaxy granite is available in both slabs and tiles to allow for creative and coordinated installations. This durable granite is suitable for both interior and exterior projects and recommended for countertops, accent walls, backsplashes, cladding, floors, and other features.', 'Black', 'Star Galaxy', 'Granite', 'India', 'Polished', 'Low', '2 CM', '2 CM', 'RSL-BGXY-COM*', 'RSL-BGXY*', '12x12', '12x12', '12x12', 'TBGXY1212', 'TBGXY1212-C', 'THDBGXY1212'),
(8, 'Black Pearl', 'Black-Pearl-Granite.jpg', 'Black Pearl granite is a predominately black granite of a semi-solid color tone with speckles of blacks, golds, silvers, browns, greens and shades of gray.  This durable granite is recommended for both indoor and outdoor use and available in a variety of finishes.', 'Black', 'Black Labrador,Black Ubatuba,Silver Pearl', 'Granite', 'India', 'Polished, Brushed', 'Low', '2 CM', '2 CM', 'RSL-SILPRL-CL*', 'RSL-SILPRL-BR*', '12x12', 'null', 'null', 'TBLKPRL1212', 'null', 'null'),
(9, 'Blanco Taupe', 'Blanco-Taupe-Granite.jpg', 'Blanco Taupe granite from China is a low variation granite of whites and grays.  It is available in both tiles and slabs and recommended for flooring, countertops and walls in both residential and commercial properties.', 'White', 'N/A', 'Granite', 'China', 'Polished', 'Low', '2 CM', '3 CM', 'RSL-BLANTAUPE-2CM*', 'RSL-BLANTAUPE-3CM*', 'null', 'null', 'null', 'null', 'null', 'null'),
(10, 'Blue Bahia', 'Blue-Bahia-Granite.jpg', 'Blue Bahia granite from Brazil features various shades of light blues and medium blues with slight variations and grains of gray and white.  This granite is good for backsplashes, countertops and flooring in both commercial and residential properties.', 'Blue', 'Azul Bahia', 'Granite', 'Brazil', 'Polished', 'Medium', '2 CM', '3 CM', 'RSL-BLUBAHIA*', 'RSL-BLUBAHIA3CM*', 'null', 'null', 'null', 'null', 'null', 'null'),
(11, 'Blue Pearl', 'Blue-Pearl-Granite.jpg', 'Blue Pearl granite from Norway features shades of blues, grays, and beige. This durable granite is an excellent choice for both commercial and residential projects including countertops, backsplashes, floors, and is an exceptional option for cladding of exterior walls.', 'Blue', 'Blue Pearl', 'Granite', 'Norway', 'Polished', 'Medium', '2 CM', '3 CM', 'RSL-BLUPRL*', 'RSL-BLUPRL-3CM*', '12x12', '18x18', 'MISC.', 'TBLUPRL1212', 'TBLUPRL18180.38', 'TGCBLUPRL1831'),
(12, 'Brown Antique', 'Brown-Antique-Granite.jpg', 'Brown Antique granite highlights the natural variations in stone with its deep brown hues and flecks of white crystal and grays.  This granite is available in both slabs and tiles and good for countertops and flooring for both indoors and outdoors.', 'Brown', 'N/A', 'Granite', 'Angola', 'Brushed', 'Low', '2 CM', '2 CM', 'RSL-BRNANT-BR*', 'RSL-BRNANT*', '12x12', 'null', 'null', 'TBRNANT1212', 'null', 'null'),
(13, 'Caledonia', 'Caledonia-Granite.jpg', 'Caledonia granite is a beautiful intricate granite of shades of grays and white ranging from charcoal to light gray. It is available in slabs in a polished finish and is recommended for all indoor and outdoor projects.', 'Gray', 'Graphite Brown,New Caledonia', 'Granite', 'Brazil', 'Polished, Brushed', 'LOW', '2 CM', '2 CM', 'RSL-CALDON*', 'RSL-CALDON-2-CL*', 'null', 'null', 'null', 'null', 'null', 'null'),
(14, 'Coffee Brown', 'Coffee-Brown-Granite.jpg', 'Coffee Brown granite features shades of brown including coffee and chocolate.  It is available in both tiles and slabs and recommended for all commercial and residential projects including flooring, walls and countertops.', 'Brown', 'N/A', 'Granite', 'India', 'Polished, Brushed', 'Low', '2 CM', '3 CM', 'RSL-COFBRN*', 'RSL-COFBRN-3CM*', 'null', 'null', 'null', 'null', 'null', 'null'),
(15, 'Colonial White', 'Colonial-White-Granite.jpg', 'Colonial White granite is a blend of cottony-pale grey, blended with cloudy silver and accented by jet black speckles.  This Indian granite is available in both slabs (2 cm and 3 cm) and granite tiles (12x12 and 18x18), and is an optimal choice for residential and commercial applications, including granite countertops.', 'White', 'Balthus,Cotton White,White Antique', 'Granite', 'India', 'Polished, Brushed', 'MEDIUM', '2 CM', '2 CM', 'PSL-COLWHT10842IS-2CM', 'RSL-COLWHT', '12x12', '18x18', 'null', 'TCOLWHT1212', 'TCOLWHT1818', 'null'),
(16, 'Costa Esmeralda', 'Costa-Esmeralda-Granite.jpg', 'Costa Esmeralda granite from Italy is a beautiful durable granite for interior and exterior projects including commercial flooring and landscaping and residential applications.  The light green and gold veining is distinctive with medium variations.', 'Green', 'N/A', 'Granite', 'Italy', 'Brushed', 'MEDIUM', '2 CM', '2 CM', 'RSL-COSSMER-BR*', 'RSL-COSSMER-BRP*', '12x12', 'null', 'null', 'TCOSTAESMR1212', 'null', 'null'),
(17, 'Crema Bordeaux', 'Crema-Bordeaux-Granite.jpg', 'Crema Bordeaux granite is a rich warm granite with deep shades of red earth tones, beiges, and grays. Crema Bordeaux is available in slabs and recommended for residential and commercial use for countertops, landscaping and wall clad applications.', 'Multi Color', 'N/A', 'Granite', 'Brazil', 'Polished', 'MEDIUM', '2 CM', '2 CM', 'RSL-CREBOR*', 'RSL-CREBOR-CL*', 'null', 'null', 'null', 'null', 'null', 'null'),
(19, 'Desert Brown', 'Desert-Brown-Granite.jpg', 'Desert Brown granite is a low variation durable granite available in both tiles and slabs in a polished finish.  It is recommended for commercial and residential projects including exterior landscaping in areas with freezing climates.', 'Brown', 'Merry Wood,Nova Brown', 'Granite', 'India', 'Polished, Brushed', 'Low', '2 CM', '2 CM', 'RSL-DESBRN2C-CL*', 'RSL-DESBRN2CM*', 'null', 'null', 'null', 'null', 'null', 'null'),
(20, 'Dynamic Blue', 'Dynamic-Blue-Granite.jpg', 'Dynamic Blue granite is a dreamy blue hued durable granite available in slabs and will add drama to any project. The deep blues and lighter blue accents are perfect for any interior or exterior project even in areas with freezing temperatures.', 'Blue', 'Brass Blue,Indian Bahia', 'Granite', 'India', 'Polished', 'MEDIUM', '3 CM', 'null', 'RSL-BLUE-3CM', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(21, 'Emerald Green', 'Emerald-Green-Granite.jpg', 'Naturally beautiful, Emerald Green granite is durable, suitable for both interior and exterior design projects, and is easy to maintain. And, it is a stunning combination of soft grays, greens, creams, and charcoal grays. Suitable to create granite countertops, waterfall islands, backsplashes, and floors, throughout residential and commercial properties.', 'Green', 'Chinese Ubatuba', 'Granite', 'China', 'Polished', 'LOW', '100x26x2CM', '100x26x3CM', 'PSL-EMEGRNDB10026-2CM', 'PSL-EMEGRNDB10026-3CM', 'null', 'null', 'null', 'null', 'null', 'null'),
(22, 'Emerald Pearl', 'Emerald-Pearl-Granite.jpg', 'Emerald Pearl granite features a dark black background that is punctuated with sparkly green and silver flecks. This durable granite is suitable to use for floors, countertops, backsplashes and walls in both interior and exterior design projects. Coordinating tiles are also available for coordinated installation projects.', 'Green', 'N/A', 'Granite', 'Norway', 'Polished', 'Low', '2 CM', '3 CM', 'RSL-EMEPRL*', 'RSL-EMEPRL-3CM*', '12x12', 'null', 'null', 'TEMPERL1212P1', 'null', 'null'),
(23, 'Giallo Fantasia', 'Giallo-Fantasia-Granite.jpg', 'Giallo Fantasia granite features a high variation with a cream background and gold, gray and dark brown fleck accents.  Giallo Fantasia is recommended for flooring, countertops and walls in interior and exterior projects.', 'Gold', 'Desert Gold,Empress Gold,Golden Garnet,Sunset Gold', 'Granite', 'China', 'Polished', 'MEDIUM', '2 CM', '3 CM', 'RSL-GIAFAN*', 'RSL-GIAFAN-3CM*', '12x12', '18x18', 'MISC.', 'TGIAFAN1212', 'TGIAFAN18180.5', 'TGCGIAFAN1831'),
(24, 'Giallo Fiorito', 'Giallo-Fiorito-Granite.jpg', 'Giallo Fiorito granite is a medium variation granite of blacks and yellows. This durable granite is available in slabs and recommended for both commercial and residential properties for all projects including flooring, landscaping and countertops.', 'Yellow', 'Giallo West', 'Granite', 'Brazil', 'Polished', 'MEDIUM', '2 CM', '2 CM', 'RSL-GIAFIO*', 'RSL-GIAFIO-CL*', 'null', 'null', 'null', 'null', 'null', 'null'),
(25, 'Giallo Napolean', 'Giallo-Napolean-Granite.jpg', 'Giallo Napoleon granite has a low variation of pattern of golds and yellows with dark gray veining.  It is available in both slabs and tiles and recommended for interior and exterior use for commercial and residential properties.', 'Yellow', 'N/A', 'Granite', 'Brazil', 'Polished', 'Low', '2 CM', '2 CM', 'RSL-GIANAP', 'RSL-GIANAP-2-CL', 'null', 'null', 'null', 'null', 'null', 'null'),
(26, 'Giallo Ornamental', 'Giallo-Ornamental-Granite.jpg', 'Giallo Ornamental granite is a veined granite with a creamy white background and dark gray and brown veins.  This granite is great for both commercial and residential applications including walls, countertops and flooring.', 'N/A', 'Giallo Santo', 'Granite', 'Brazil', 'Polished', 'Medium', '2 CM', '2 CM', 'RSL-GIAORN-2-COM*', 'RSL-GIAORN-CL*', '12x12', 'null', 'null', 'TGIAORN1212', 'null', 'null'),
(27, 'Giallo Veneziano', 'Giallo-Veneziano-Granite.jpg', 'Giallo Veneziano granite is a durable granite recommended for commercial and residential projects including flooring, landscaping, walls, and countertops.  Giallo Veneziano from Brazil is a medium variation granite with a rich golden background and black and gray veins.', 'Yellow', 'N/A', 'Granite', 'Brazil', 'Polished', 'Medium', '2 CM', '2 CM', 'RSL-GIAVEN*', 'RSL-GIAVEN-COM*', '12x12', '12x12', '18x18', 'TGIAVEN1212', 'TGIAVEN1212CL', 'TGIAVEN181850'),
(28, 'Gibli', 'Gibli-Granite.jpg', 'Gibli granite is a beige and ivory durable granite with darker accents of medium variation.  It is available in both tiles and slabs with a polished finish and recommended for residential and commercial properties including high traffic areas for flooring, countertops and walls.', 'Beige', 'Ghibli,Gibili,Ivory Cream ,Ivory Silk,Rare Ivory', 'Granite', 'India', 'Polished', 'Medium', '2 CM', '3 CM', 'RSL-GIBLI*', 'RSL-GIBLI-3C-CL*', 'null', 'null', 'null', 'null', 'null', 'null'),
(29, 'Impala Black', 'Impala-Black-Granite.jpg', 'Impala Black granite from South Africa features shades of dark grays and blacks with low variation in pattern.  This durable granite is recommended for use indoors and outdoors for a variety of projects including flooring, walls, countertops and landscaping projects.', 'Black', 'Black Impala', 'Granite', 'South Africa', 'Polished', 'LOW', '2 CM', '3 CM', 'RSL-IMPALA*', 'RSL-IMPALA-3CM*', '12x12', 'null', 'null', 'TIMPALA1212', 'null', 'null'),
(30, 'Imperial Coffee', 'Imperial-Coffee-Granite.jpg', 'Imperial Coffee granite is a beautiful brown granite with dark and light flecks for added dimension.  This durable granite is recommended for indoor and outdoor use including landscaping, outdoor countertops, walls, and flooring even in areas with freezing temperatures.', 'Brown', 'Imperial Brown,Imperial Cafe', 'Granite', 'Brazil', 'Polished', 'MEDIUM', '2 CM', '3 CM', 'RSL-IMPCOF', 'RSL-IMPCOF-3CM', 'null', 'null', 'null', 'null', 'null', 'null'),
(31, 'Imperial Gold', 'Imperial-Gold-Granite.jpg', 'Imperial Gold granite features shades of gold and yellow background with white and gray veins and small flecks of darker gold. This durable granite from India is available in slabs and is recommended for interior and exterior projects including landscaping, walls, countertops, and flooring.', 'Gold', 'Golden Sun ,Imperial Gold,Nevada Gold', 'Granite', 'India', 'Polished', 'MEDIUM', '3 CM', '112x26x2CM', 'RSL-IMPGLD-3CM*', 'PSL-IMPGLDDB11226-2CM', 'null', 'null', 'null', 'null', 'null', 'null'),
(32, 'Labrador Antique', 'Labrador-Antique-Granite.jpg', 'Labrador Antique granite from Norway is a low variation durable granite with shades of browns, pinks and small flecks of blues.  This durable slab granite is recommended for interior and exterior projects including flooring, countertops, landscaping and walls.', 'Brown', 'Labrador Antico', 'Granite', 'Norway', 'Polished', 'LOW', '2 CM', 'null', 'RSL-LABANITQUE*', 'null', '12x12', 'null', 'null', 'TLABANT1212', 'null', 'null'),
(34, 'New Imperial Red', 'New-Imperial-Red-Granite.jpg', 'New Imperial Red Granite from India is a dramatic and lively red granite with blue accents.  It is available in both 12x12 and 18x18 tiles and is recommended for interior and exterior projects including floors, walls and countertops.', 'Red', 'Jhansi Red', 'Granite', 'India', 'Polished', 'Low', 'null', 'null', 'null', 'null', '12x12', 'null', 'null', 'TNEWIMPRED1212', 'null', 'null'),
(35, 'New Venetian Gold', 'New-Venetian-Gold-Granite.jpg', 'New Venetian Gold granite features beige and golden tones with light veining of deep reds, grays and browns.  This granite is available in a polished finish and both slabs and tiles.', 'Gold', 'Ouro Brazil,Venetian Gold', 'Granite', 'Brazil', 'Polished', 'Medium', '2 CM', '2 CM', 'RSL-NEWVENEGLD*', 'RSL-NEWVEN-2-COM*', '12x12', '12x12', '18x18', 'TNEWVENGLD1212', 'TNEWVNGLD1212-C', 'TNEWVENGLD1818'),
(36, 'Peach Purse', 'Peach-Purse-Granite.jpg', 'Peach Purse Granite is a medium variation granite of soft peaches, browns and ivories with black veins.  This durable granite is available in both tiles and slabs and recommended for commercial and residential properties including exterior applications including walls, countertops and landscaping projects.', 'Salmon', 'Rosa Fresca', 'Granite', 'China', 'Polished', 'Medium', '2 CM', '3 CM', 'RSL-PEACHPRS-2CM*', 'RSL-PEACHPRS-3CM*', '12x12', 'null', 'null', 'TPEACHPRS1212', 'null', 'null'),
(37, 'Premium Black', 'Premium-Black-Granite.jpg', 'Premium Black Granite is a solid deep black, low variation durable granite.  Available in slabs, mosaics, prefabricated countertops and a variety of tile sizes it is perfect for both interior and exterior usage and offer the ultimate in flexibility for coordination.', 'Black', 'Absolute Black,Jet Black,Telephone Black', 'Granite', 'India', 'Polished, Brushed, Flame', 'Low', '2 CM', '2 CM', 'RSL-PREMBLKHON', 'RSL-PREMBLK.8-F', '12x12', '12x12', '12x12', 'TTILBLK1212FL', 'TPBLACK1212HN', 'TPBLACK1212'),
(38, 'Premium Plus Black', 'Premium-Plus-Black-Granite.jpg', 'Premium Plus Black Granite is a deep solid black durable granite available in both tiles and slabs.  It is recommended for interior and exterior projects including in areas with freezing temperatures for outdoor kitchens and landscaping.', 'Black', 'Absolute Black,Jet Black,Nero Absolte', 'Granite', 'India', 'Polished', 'Low', '2 CM', '3 CM', 'RSL-PPBLK', 'RSL-PPBLK-3CM', 'null', 'null', 'null', 'null', 'null', 'null'),
(39, 'Raja Pink', 'Raja-Pink-Granite.jpg', 'Raja Pink Granite is a subtle mid-toned pink, white and gray granite of low variation available in both tiles and slabs.  Raja Pink is recommended for both interior and exterior uses including countertops, walls, flooring and landscaping projects in areas with temperatures below freezing.', 'Salmon', 'Raja Pink,Royal Juprana,Savakasi Pink', 'Granite', 'India', 'Polished', 'Low', '3 CM', '3 CM', 'RSL-RAJPNK-3CM*', 'RSL-RAJPNK-3CM-CL*', 'null', 'null', 'null', 'null', 'null', 'null'),
(40, 'Raja Yellow', 'Raja-Yellow-Granite.jpg', 'Raja Yellow Granite from India is a low variation durable granite of shades of ivory, whites and yellows with subtle veins to add elegance and intrigue to kitchens, bathrooms, and exterior projects.  It is available in both slabs and tiles for ultimate coordination possibilities for flooring, walls, countertops and landscaping projects.', 'Yellow', 'Ivory Brown,Shivakashi,Sivakasi Yellow', 'Granite', 'India', 'Polished', 'LOW', '3 CM', '112x26x2CM', 'RSL-RAJYEL-3CM*', 'PSL-RAJYELDB11226-2CM', 'null', 'null', 'null', 'null', 'null', 'null'),
(41, 'River White', 'River-White-Granite.jpg', 'River White granite from India has low variations in its white and gray veining with small deep burgundy flecks.  River white is a durable granite that is recommended for interior and exterior projects and is available in both tiles and slabs.', 'White', 'N/A', 'Granite', 'India', 'Polished, Brushed, Honed', 'Low', '2 CM', '2 CM', 'RSL-RIVWHI*', 'RSL-RIVWHI-C*', '12X24', 'null', 'null', 'TRIVWHT1224', 'null', 'null'),
(42, 'Rosewood', 'Rosewood-Granite.jpg', 'Rosewood granite from India features shades of peach with light gray veins.  It is recommended for all commercial and residential projects including outdoor countertops and walls in climates with freezing temperatures.', 'Red', 'N/A', 'Granite', 'India', 'Polished', 'Low', '3 CM', 'null', 'RSL-ROSWOD-3CM*', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(43, 'Sapphire Blue', 'Sapphire-Blue-Granite.jpg', 'Sapphire blue granite is an elegant combination of blues, grays, blacks and brown.  From India, this durable and versatile granite features a small intricate pattern of flecks', 'Blue', 'Sapphire Brown', 'Granite', 'India', 'Polished', 'Low', '2 CM', '2 CM', 'RSL-SAPBLU-CL*', 'RSL-SAPBLU*', '12X12', 'null', 'null', 'TSAPBLU1212-C', 'null', 'null'),
(44, 'Steel Grey', 'Steel-Grey-Granite.jpg', 'Steel Grey granite from India is a low variation durable granite with shades of grays and small flecks of lighter grays. It is available in slabs in a polished finish and recommended for interior and exterior projects for both commercial and residential projects including landscaping, flooring, countertops and walls.', 'Gray', 'N/A', 'Granite', 'India', 'Polished, Brushed', 'LOW', '2 CM', '3 CM', 'RSL-STELGREY*', 'RSL-STELGREY-3CM-BR*', 'null', 'null', 'null', 'null', 'null', 'null'),
(45, 'Tan Brown', 'Tan-Brown-Granite.jpg', 'Tan Brown granite features dark brown, black and grey flecks. This durable natural granite works well in a variety of interior and exterior projects including walls, floors, countertops, and other architectural features.', 'Brown', 'N/A', 'Granite', 'India', 'Polished, Brushed', 'Low', '2 CM', '2 CM', 'RSL-TAN-CL*', 'RSL-TAN-BR*', '12x12', '12x12', '18x18', 'TTANBRN1212', 'TTANBRN1212-C', 'TTANBRN181850'),
(46, 'Typhoon Green', 'Typhoon-Green-Granite.jpg', 'Typhoon Green granite from India is available in slabs with creams, grays and greens and small flecks of deep burgundy. Typhoon Green is available in countertop slabs with a polished finish and is recommended for interior and exterior projects including outdoor and indoor kitchen countertops and all interior applications.', 'Green', 'Surf Green', 'Granite', 'India', 'Polished', 'MEDIUM', '2 CM', '112X6X2CM', 'RSL-TYPGRN*', 'PSL-TYPGRN1126BS-2CM', 'null', 'null', 'null', 'null', 'null', 'null'),
(47, 'Ubatuba', 'Ubatuba-Granite.jpg', 'Ubatuba granite from Brazil is a finely textured granite featuring  black, gold, gray and green speckles.  The shimmering speckles of Ubatuba granite make it a perfect statement piece for indoor and outdoor applications.', 'Green', 'Bahia Green,Labrador Green,Verde Ubatuba', 'Granite', 'Brazil', 'Polished, Brushed, Flame', 'Low', '2 CM', '2 CM', 'RSL-UBATUBA-CL*', 'RSL-UBATUB-BR*', '12x12', '18x18', 'null', 'TUBATUBA1212', 'TUBATUBA181875', 'null'),
(48, 'Verde Butterfly', 'Verde-Butterfly-Granite.jpg', 'Verde Butterfly Granite is an exquisite blend of greens, grays and whites with darker black veins ideal for kitchen and bathroom applications.  This dynamic granite is available in both slabs and tiles for coordination and is recommended for both commercial and residential applications including exterior projects, countertops, flooring, and walls.', 'Green', 'Green Butterfly', 'Granite', 'Brazil', 'Polished', 'Low', '2 CM', '3 CM', 'RSL-VERBUTFLY*', 'RSL-VERBFLY-3CL*', '12x12', 'null', 'null', 'TVERBUTFLY1212', 'null', 'null'),
(49, 'Volga Blue', 'Volga-Blue-Granite.jpg', 'Volga Blue granite  from the Ukraine is an exquisite durable granite in shades of dark grays and blues with lighter variations in grays and blues.  This granite is available in both tiles and slabs and is recommended for commercial and residential properties, both indoors and out in climates with freezing temperatures.', 'Blue', 'N/A', 'Granite', 'Ukraine', 'Polished', 'Low', '2 CM', '3 CM', 'RSL-VOLBLU*', 'RSL-VOLBLU-3CM*', '12x12', 'null', 'null', 'TVOLBLU1212', 'null', 'null'),
(50, 'Vyara Juparana', 'Vyara-Juparana-Granite.jpg', 'Vyara Juparana is a durable orange and green granite that is very durable from India.  It is available in both tiles and slabs and is recommended for commercial and residential projects both for interior and exterior applications including landscaping, walls, flooring and countertops.', 'Green', 'Indian Parana', 'Granite', 'India', 'Polished', 'LOW', '2 CM', 'null', 'RSL-VYARA*', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(51, 'Yellow River', 'Yellow-River-Granite.jpg', 'Yellow River granite is an exquisite durable granite from Brazil of browns, yellows, golds and dark grays.  It is available in both tiles and slabs and is recommended for a variety of indoor and outdoor projects including commercial flooring, countertops, walls, and landscaping.', 'Yellow', 'Golden Ridge,Golden River', 'Granite', 'Brazil', 'Brushed', 'HIGH', '2 CM', '2 CM', 'RSL-YELRIVER*', 'RSL-YELRIVER-CL*', 'null', 'null', 'null', 'null', 'null', 'null'),
(52, 'endian', 'endian.PNG', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `files`
--
ALTER TABLE `files`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `files`
--
ALTER TABLE `files`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
